# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-10-07 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='created',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='created',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='quizprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='quizprofile',
            name='modified',
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='attempted_by', to='quiz.Choice'),
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='For text-answer questions, store the expected correct answer here.', max_length=1024, null=True, verbose_name='Correct Text Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('TX', 'Text Answer')], default='SC', max_length=2, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.Choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is correct?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='quizprofile',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quizprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
            preserve_default=False,
        ),
    ]
