# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-10-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20251007_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprofile',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
