# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-10-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20251007_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, to='quiz.Choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
