# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20251031_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='html',
            field=models.TextField(verbose_name='Kérdés szövege'),
        ),
        migrations.AlterField(
            model_name='question',
            name='maximum_marks',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6, verbose_name='Maximum Pontszám'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='immediate_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
