# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20251107_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizquestions', to='quiz.Question'),
        ),
    ]
