# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-10 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_auto_20251108_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Azok a csoportok, amelyek tagjai kitölthetik a kvízt.', related_name='quizzes_allowed', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Azok a felhasználók, akik kitölthetik ezt a kvízt.', related_name='quizzes_allowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
