# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20251111_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, help_text='Ha szöveges kérdés, ide írd a helyes választ.', max_length=255, null=True),
        ),
    ]
