# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_correct_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedquestion',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
