# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_attemptedquestion_text_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(max_length=255)),
                ('right_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='quiz.Question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
