# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_matchingpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='matching_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptedmatch',
            name='attempted_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_matches', to='quiz.AttemptedQuestion'),
        ),
        migrations.AddField(
            model_name='attemptedmatch',
            name='chosen_right_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.MatchingPair'),
        ),
        migrations.AddField(
            model_name='attemptedmatch',
            name='left_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.MatchingPair'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptedmatch',
            unique_together=set([('attempted_question', 'left_pair')]),
        ),
    ]
