# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-12 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20251112_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='matching_answer',
        ),
    ]
